config/routes.rb
Rails.application.routes.draw do
  
  resources :pins

  devise_for :users
root 'pins#index'
get 'about' => 'pages#about'

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	validates :description, presence: true
	validates :user_id, presence: true
	has_attached_file :image, :styles => { :medium => "300x300>"}

		validates_attachment :image, :presence => true,
  :content_type => { :content_type => ["image/png","image/jpeg","image/jpg"] },
  :size => { less_than: 5.megabytes }

belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password) }

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def action
  end
end

app/controllers/pins_controller.rb
 class PinsController < ApplicationController
  before_filter :authenticate_user!,except: [:index]
  before_action :set_pin, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @pins = Pin.order("created_at desc")
    respond_with(@pins)
  end

  def show
    respond_with(@pin)
  end

  def new
    @pin = current_user.pins.new
    respond_with(@pin)
  end

  def edit
    @pin = current_user.pins.find(params[:id])
  end

  def create
    @pin = current_user.pins.new(pin_params)
    @pin.save
    respond_with(@pin)
  end

  def update
    @pin = current_user.pins.find(params[:id])
    respond_with(@pin)
  end

  def destroy
        @pin = current_user.pins.find(params[:id])
    @pin.destroy 
    respond_with(@pin)
  end

  private
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def pin_params
      params.require(:pin).permit(:description ,:image)
    end

end


#def create
  #@user = User.create( user_params )
#end

#private

# Use strong_parameters for attribute whitelisting
# Be sure to update your create() and update() controller methods.

#def user_params
  #params.require(:user).permit(:avatar)
#end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block"> <button type="button"
    class="close" data-dismiss="alert">x</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
		<small>
			<%= link_to "Website", "http://onemonthraills.com" %>
by <%= link_to "Ramon S. DeBelen", "http://onemonthraills.com" %>

</small>
</div> 

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Game Trade</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %> </li>
        <li><%= link_to "About", about_path %> </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Games <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Playstation 4</a></li>
            <li><a href="#">Playstation 3</a></li>
            <li><a href="#">Playstation Vita</a></li>
                   <li class="divider"></li>
            <li><a href="#">Xbox One</a></li>
            <li><a href="#">Xbox 360</a></li>
            <li class="divider"></li>
            <li><a href="#">PC </a></li>
            <li class="divider"></li>
            <li><a href="#">Wii U</a></li>
            <li><a href="#">Nintendo 3DS</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li><%= link_to "Add +", new_pin_path %> </li>
            <li><%= link_to "Edit Profile", edit_user_registration_path %> </li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %> </li>
            <% else %>
            <li><%= link_to "Login", new_user_session_path %> </li>
        <% end %>
         
       
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
      <ul>
        <li>
          <%= value %>
        </li>
      </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Game Trade</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
<div class="container">
	<%= render 'layouts/messages' %>
<%= yield %>

</div>
<%= render 'layouts/footer' %>

</body>
</html>

app/views/pages/_home.html.erb
<% if user_signed_in? %>

   <% else %>

		<div class="jumbotron">
			
		   <h1>Buy,Sell and Trade your Games!</h1>
		     You've found the home page for the 
		     <%= link_to "Game Trading", "http://onemonthraills.com" %>
		     application.
		  
		    <p>
		     <%= link_to "Sign Up Now!", new_user_registration_path, class: "btn btn-primary btn-lg" %>
		    	
		    </p>

		</div>
<% end %>

app/views/pages/about.html.erb
<h1> About </h1>
<p>
	<%= link_to "One Month Rails", "http://onemonthraills.com" %> is a project to teach <%= link_to "Ruby on Rails", "http://rubyonraills.org" %> in one month.
	This is the sample application.
</p>

	

app/views/pages/home.html.erb
<% if user_signed_in? %>
   <h1> You're logged in! </h1>
   <% else %>

		<div class="jumbotron">
			
		   <h1>Buy,Sell and Trade your Games!</h1>
		     You've found the home page for the 
		     <%= link_to "Game Trading", "http://onemonthraills.com" %>
		     application.
		  
		    <p>
		     <%= link_to "Sign Up Now!", new_user_registration_path, class: "btn btn-primary btn-lg" %>
		    	
		    </p>

		</div>
<% end %>

app/views/pins/_form.html.erb
<%= simple_form_for(@pin,html:{class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>

  <%= f.input :image %> 
  
  <div class="form-inputs well">
  	
    <%= f.input :description, as: :text, input_html: { rows: "3"}  %>
</div>
  </div>


  <div class="form-actions well">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
 
<% end %>

app/views/pins/_pin.html.erb
   <div class="box">

   <%= link_to (image_tag pin.image(:medium)), pin %>
   <p class="description">
        <%= pin.description %>
    </p>
    <p>
    	<strong>
    	Posted by <%= pin.user.name %>
    </strong>
</p>
         <% if current_user == pin.user %>
<p>
         <%= link_to 'Edit', edit_pin_path(pin) %>
          <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
  </p>
   </div>
 

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
  <%= render 'pages/home' %>

 <div id="pins">
<%= render @pins %>
</div>
      
  

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-sm-offset-2 col-sm-6">
	<div class="well">
		<%= image_tag @pin.image %>
<p>
 
  <%= @pin.description %>
<% if current_user == @pin.user %>
		<%= link_to 'Edit', edit_pin_path(@pin) %> 
<% end %>
		<%= link_to 'Back', pins_path %>

</p>
</div>
</div>
</div>